#!/usr/bin/with-contenv sh

# From https://github.com/smebberson/docker-alpine/tree/master/alpine-apache

exec /usr/bin/svnserve -d --foreground -r /home/svn --compression 0 --memory-cache-size=256 --listen-port 3690;
